# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# ==== Main Mod properties ====
archives_name=roadarchitect
maven_group=net.oxcodsnet.roadarchitect

# ==== Minecraft properties ====
minecraft_version=1.21.1
neoform_version=1.21.1-20240808.144430

# ==== Dependencies ====
junit_version=5.10.2
caffeine_version=3.2.3

# ==== COMMON MOD META ====
mod_authors=0xCoDSnet
mod_description=Travel around the world without barriers: RoadArchitect automatically scans your world, finds villages, and other structures, and then lays a network of roads between them.
mod_homepage=https://github.com/0xCoDSnet
mod_id=roadarchitect
mod_license=Apache-2.0
mod_name=RoadArchitect
mod_sources=https://github.com/0xCoDSnet/RoadArchitect
mod_version=1.6.2

# ==== For ALL ====
cloth_config_version=15.0.140

# ==== For Fabric ====
fabric_api_version=0.116.5+1.21.1
fabric_loader_version=0.16.14
modmenu_version=11.0.3

# ==== For NeoForge ====
neoforge_version=21.1.187
